### ISSUE TITLE
Silverpeas official image for ARMv8 aarch64

### ISSUE THREAD

**Issue by khasim** [Silverpeas/docker-silverpeas-prod#1]
Hi,

Silverpease works for ARMv8 after setting JAVA_HOME to point to arm64 version,

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64/

Can I submit a PR to set JAVA_HOME based on architecture ? 

Regards,
Khasim

**Comment by odidev** [comment]
Hi @khasim,

I have a concern about this.
How did you verify working of ```Silverpeas``` on ```arm64v8```?

Did ```Silverpeas``` build for you without any errors except ```JAVA_HOME```, or have you done any other changes too?

Can you post some relevant data to confirm the working of this package?

**Comment by khasim** [comment]
Hello @odidev 

Here is what I followed to build

git diff
diff --git a/Dockerfile b/Dockerfile
index 418bbeb..3780cc2 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -61,7 +61,8 @@ ENV LC_ALL ${DEFAULT_LOCALE}
 
  //Set up environment variables for Silverpeas
-ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
+#ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
+ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64
 ENV SILVERPEAS_HOME /opt/silverpeas

docker build -t silverpeas .

Removing intermediate container 4649f9bdd639
Step 26/26 : CMD /opt/run.sh
 ---> Running in a7100f223ef7
 ---> dc4bc15ddc4b
Removing intermediate container a7100f223ef7
Successfully built dc4bc15ddc4b

docker images
silverpeas                 latest              dc4bc15ddc4b        58 seconds ago      1.45 GB

Please let me know what issue you are facing,

**Comment by odidev** [comment]
Well @khasim , I am surprised to see a successful build for ```silverpeas```.

I can clearly observe issue in this command:
``` silverpeas assemble```

while fetching ```JackRabbit``` package for both ```AMD64 & ARM64``` architectures.

Now I wonder how it built for you.

**Comment by odidev** [comment]
Hi @khasim ,

If your package is building and running fine then can you raise a **PR** for ARM64v8 ?
Then we can see whether it goes ahead or not.

In addition, going by very low activity for this package I wonder how much time will be taken to resolve your PR. But still give it a try.

You will be required to raise a PR at this link as well w.r.t. to ```arm64v8```
https://github.com/docker-library/official-images/blob/master/library/silverpeas

**Comment by odidev** [comment]
@khasim - 1 more thing...
Can you post complete build logs for ```silverpeas``` over ```arm64v8```?

**Comment by odidev** [comment]
@mmoqui 
Hi Miguel,

I do agree with the concerns raised by you.

Regarding demand for ARM64, I would say that most of the Docker modules have started to work in the direction of ARM64 as it is getting popular in the market.

I appreciate your position and what you said above makes sense. The only thing that I would add would be to comment for people possibly experimenting with ```silverpeas``` on Raspberry PIs or even larger systems like ThunderX (96 cores via packet.net which are cheap and efficient)

I would hope that people will be able to build this themselves without too much extra trouble but here's additional information:
```
Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/
```
Would really love to see SilverPeas on ARM! :)

In case you plan to change your mind and plan to support ```arm64v8```, do let me know.
Thank you again and I hope we can help generate demand for Silverpeas on Arm.

Regards,

**Comment by mmarmm** [comment]
@mmoqui Hi Miguel, you make a good point but I'd like to point out that OwnCloud, Wordpress, and other related applications support arm64v8 along with all the major applications that top the official images list (nginx, alpine, busybox, httpd, redis, mongo, ubuntu, node, ...). I can't promise you a million users tomorrow if you support the architecture but the Arm community is wide spread and motivated so you may be surprised. Between the free resources and the fact that it's currently working I hope I can convince you to provide an image even if it's marked experimental? Thank you.

**Comment by odidev** [comment]
Hi @mmoqui 

I have raised a PR at https://github.com/Silverpeas/docker-silverpeas-prod/pull/2, so that we have a set of changes required, in case you plan to ```silverpeas``` over ```arm64v8``` in future.

Do let me know when you are ready to plan the same, as I will be ready to support you in every possible way in terms of platform/build/run verification.

Regards,

**Comment by mmoqui** [comment]
With the PR of odidev, from your proposition khasim, Silverpeas can now be built and ran on ARM64 architecture.
