### ISSUE TITLE
Silverpeas on docker gives 404 & management also inaccessible.

### ISSUE THREAD

**Issue by vemman** [Silverpeas/docker-silverpeas-prod#6]
I am trying to test Silverpeas. I followed the instructions as given on the docker page. But after setting both Postgres and Silverpeas, I get a 404 error. Both via mapped port to host and from within the container (I used Lynx inside the container and I got the same result).

I checked the Postgres container and can see that tables (236 of them) are created.
I am not proficient not Java dev but let me know what log files are needed.

Any help is appreciated
Thank You
V

System Configuration
AMD Ryzen 5 5600, 16GB, Windows 10 + WSL2 + Docker Desktop

Logs
[silverpeas-error.log](https://github.com/Silverpeas/docker-silverpeas-prod/files/12278890/silverpeas-error.log)
[docker-sp.log](https://github.com/Silverpeas/docker-silverpeas-prod/files/12278891/docker-sp.log)
[wildfly-server.log](https://github.com/Silverpeas/docker-silverpeas-prod/files/12278892/wildfly-server.log)
[silverpeas-trace.log](https://github.com/Silverpeas/docker-silverpeas-prod/files/12278893/silverpeas-trace.log)
[jboss-output.log](https://github.com/Silverpeas/docker-silverpeas-prod/files/12278895/jboss-output.log)

**Comment by SilverDav** [comment]
Hello Raman,

I found no error in the logs.. which url did you use to test ?

Don't forget to specifiy the web context:   http://localhost:8000/silverpeas

**Comment by vemman** [comment]
> Hello Raman,
> 
> I found no error in the logs.. which url did you use to test ?
> 
> Don't forget to specifiy the web context: http://localhost:8000/silverpeas

Hi,
thanks for the reply. I was using http://localhost:port/.
The docker hub documentation was not telling to use "/silverpeas" folder. I should've gone in full with the silverpeas.org installation doc.

Thanks for the help. Let me continue to explore this.
